config/routes.rb
Rails.application.routes.draw do
  get "/test_reg", to: "users/registrations#new"

  root "top#index"

  resources :posts

  devise_for :users, controllers: {
    registrations: "users/registrations"
  }

  resource :mypage, only: [:show], controller: :users

  resources :tags, only: [:create]

  resources :tweets do
    resources :likes, only: [:create, :destroy]
    resources :comments, only: [:create, :destroy]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :tweet
  # --- 追加：content（内容）が空ではないことを確認 ---
  validates :content, presence: true
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :tweet
  belongs_to :user
  validates_uniqueness_of :tweet_id, scope: :user_id
end

app/models/post.rb
class Post < ApplicationRecord
    mount_uploader :video, VideoUploader
end

app/models/tag.rb
class Tag < ApplicationRecord

  validates :name, presence: true, uniqueness: { case_sensitive: false }
  #Tagsテーブルから中間テーブルに対する関連付け
  has_many :tweet_tag_relations, dependent: :destroy
  #Tagsテーブルから中間テーブルを介してArticleテーブルへの関連付け
  has_many :tweets, through: :tweet_tag_relations, dependent: :destroy

end

app/models/tweet.rb
class Tweet < ApplicationRecord
  belongs_to :user

  has_many :tweet_tag_relations, dependent: :destroy
  has_many :tags, through: :tweet_tag_relations, dependent: :destroy

  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :liked_users, through: :likes, source: :user

  mount_uploader :video, VideoUploader
  has_one_attached :video

  validate :at_least_one_content_set

  private

  def at_least_one_content_set
    # テキストセットが揃っているか
    text_set_present = genre.present? && purpose.present? && place.present?

    # 動画セットがあるか
    video_set_present = youtube_url.present? || video.present?

    if !text_set_present && !video_set_present
      errors.add(:base, "テキスト情報または動画情報を入力してください")
    end
  end
end

app/models/tweet_tag_relation.rb
class TweetTagRelation < ApplicationRecord
  belongs_to :tweet
  belongs_to :tag
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :tweets
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :liked_tweets, through: :likes, source: :tweet
  has_many :tweets, dependent: :destroy
  validates :name, presence: true
  validates :profile, length: { maximum: 200 }
  has_one_attached :image 
  def already_liked?(tweet)
    likes.exists?(tweet_id: tweet.id)
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!

  def create
    tweet = Tweet.find(params[:tweet_id])
    comment = tweet.comments.build(comment_params) #buildを使い、contentとtweet_idの二つを同時に代入
    comment.user_id = current_user.id
    if comment.save
      flash[:success] = "コメントしました"
      redirect_back(fallback_location: root_path) #直前のページにリダイレクト
    else
      flash[:success] = "コメントを入力してください"
      redirect_back(fallback_location: root_path) #直前のページにリダイレクト
    end
  end

  def destroy
  comment = Comment.find(params[:id])
  # ログインしているユーザーがコメントの投稿者である場合のみ削除を許可
  if comment.user_id == current_user.id
    comment.destroy
    flash[:success] = "コメントを削除しました"
  else
    flash[:error] = "権限がありません"
  end
  redirect_back(fallback_location: root_path)
end

  private

    def comment_params
      params.require(:comment).permit(:content)
    end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController

  def create
    like = current_user.likes.create(tweet_id: params[:tweet_id]) #user_idとtweet_idの二つを代入
    redirect_back(fallback_location: root_path)
  end

  def destroy
    like = Like.find_by(tweet_id: params[:tweet_id], user_id: current_user.id)
    like.destroy
    redirect_back(fallback_location: root_path)
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: %i[ show edit update destroy ]

  # GET /posts or /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1 or /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts or /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: "Post was successfully created." }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1 or /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: "Post was successfully updated.", status: :see_other }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1 or /posts/1.json
  def destroy
    @post.destroy!

    respond_to do |format|
      format.html { redirect_to posts_path, notice: "Post was successfully destroyed.", status: :see_other }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def post_params
      params.require(:post).permit(:video)
    end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  before_action :authenticate_user!, only: [:create]  # ログインユーザーだけ追加できる（不要なら消してOK）

  def create
    if params[:name].present?
      Tag.find_or_create_by(name: params[:name].strip)
    end
    redirect_to tweets_path
  end
end

app/controllers/top_controller.rb
class TopController < ApplicationController
  def index
  end
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create]

  def index
  @tweets = Tweet.all

  if params[:tag_ids].present?
    @tweets = @tweets.joins(:tags).where(tags: { id: params[:tag_ids] }).distinct
  end
end


  def new
    @tweet = Tweet.new
  end

  def create
    @tweet = current_user.tweets.build(tweet_params)

    if @tweet.save
      redirect_to action: "index"
    else
      redirect_to action: "new"
    end
  end

  def show
    @tweet = Tweet.find(params[:id])
    @comments = @tweet.comments
    @comment = Comment.new
  end

  def destroy
    tweet = Tweet.find(params[:id])
    tweet.destroy if tweet.user_id == current_user.id
    redirect_to action: "index"
  end

  private

  def tweet_params
    params.require(:tweet).permit(:genre, :purpose, :place, :youtube_url, :body, :video, tag_ids: [])
  end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def show
    @user = current_user
    @tweets = @user.tweets.order(created_at: :desc)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/helpers/top_helper.rb
module TopHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
  def find_youtube_url(youtube_url)
    if youtube_url[0..16] == "https://youtu.be/"
      return youtube_url[17..27]
      # "https://youtu.be/WGiUk8VakxQ" 11桁のyoutubeのURLが出力されるようにする
    else
      return youtube_url[32..42]
      # "https://www.youtube.com/watch?v=WGiUk8VakxQ" 11桁のyoutubeのURLが出力されるようにする
    end
  end
end

app/helpers/users/registrations_helper.rb
module Users::RegistrationsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation" data-turbo-cache="false">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= button_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), data: { turbo: false } %><br />
  <% end %>
<% end %>

app/views/users/show.html.erb
<div class="user-wrapper">

  <!-- 左:PROFILE + ナビ -->
  <aside class="user-side">

    <div class="profile-box">
      <h2 class="profile-title">PROFILE</h2>

      <div class="profile-item">
        <div class="profile-label">User Name:</div>
        <div class="profile-value"><%= @user.name %></div>
      </div>

      <%# 画像の持ち方がアプリで違うので、ここは2パターン用意 %>
      <div class="profile-item">
        <div class="profile-label">ICON:</div>
        <div class="profile-value">
          <% if @user.respond_to?(:image) && @user.image.present? %>
            <%= image_tag @user.image.url, class: "profile-icon" %>
          <% elsif @user.respond_to?(:avatar) && @user.avatar.attached? %>
            <%= image_tag url_for(@user.avatar), class: "profile-icon" %>
          <% else %>
            <div class="profile-icon placeholder"></div>
          <% end %>
        </div>
      </div>


      <div class="profile-item">
        <div class="profile-label">Profile:</div>
        <div class="profile-value"><%= @user.profile %></div>
      </div>

      <%# もし編集リンクがあるなら %>
      <% if user_signed_in? && current_user.id == @user.id %>
        <div class="profile-actions">
          <%= link_to "Edit", edit_user_registration_path, class: "profile-edit" %>
        </div>
      <% end %>
    </div>

    <nav class="user-nav">
      <%= link_to "TOP", root_path, class: "user-nav-link" %>
      <%= link_to "POST", new_tweet_path, class: "user-nav-link" %>
    </nav>

  </aside>

  <!-- 右：投稿一覧 -->
  <main class="user-main">
    <h2 class="user-post-title">ユーザーの投稿一覧</h2>

    <div class="user-video-grid">
      <% @tweets.each do |t| %>
        <div class="user-video-card">

          <div class="user-video-container">
            <% if t.video? %>
              <%= video_tag url_for(t.video), controls: true %>
            <% elsif t.youtube_url.present? && t.youtube_url.include?("/") %>
              <iframe
                src="https://www.youtube.com/embed/<%= find_youtube_url(t.youtube_url) %>"
                allowfullscreen>
              </iframe>
            <% end %>
          </div>
          <p class="post-user"><%= t.user.name %></p>
        </div>
      <% end %>
    </div>
  </main>

</div>